project_id = "xbtendfjajspaidpktsw"

[functions.generate-tutorial-image]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.debug-admin]
verify_jwt = false
